import sys
from pyqtgraph import PlotWidget
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(992, 644)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/WindowIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("color: white;\n"
"background-color: #1e1e2f;\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tabWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border: none;\n"
"\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #1e1e2f;\n"
"\n"
"}\n"
"QTabBar::tab {\n"
"    border: none;\n"
"    padding-right:9px;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.design_tab = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.design_tab.setPalette(palette)
        self.design_tab.setObjectName("design_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.design_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.design_box = QtWidgets.QGroupBox(self.design_tab)
        self.design_box.setObjectName("design_box")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.design_box)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Zplane_box = QtWidgets.QGroupBox(self.design_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Zplane_box.sizePolicy().hasHeightForWidth())
        self.Zplane_box.setSizePolicy(sizePolicy)
        self.Zplane_box.setStyleSheet("border:none;")
        self.Zplane_box.setObjectName("Zplane_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Zplane_box)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.z_plane = PlotWidget(self.Zplane_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_plane.sizePolicy().hasHeightForWidth())
        self.z_plane.setSizePolicy(sizePolicy)
        self.z_plane.setMinimumSize(QtCore.QSize(265, 264))
        self.z_plane.setMaximumSize(QtCore.QSize(253, 16777215))
        self.z_plane.setObjectName("z_plane")
        self.verticalLayout_4.addWidget(self.z_plane)
        self.verticalLayout_3.addWidget(self.Zplane_box)
        self.preferenceBox = QtWidgets.QGroupBox(self.design_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preferenceBox.sizePolicy().hasHeightForWidth())
        self.preferenceBox.setSizePolicy(sizePolicy)
        self.preferenceBox.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.preferenceBox.setObjectName("preferenceBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.preferenceBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.preferenceBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.preferenceBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.Clear_combobox = QtWidgets.QComboBox(self.preferenceBox)
        self.Clear_combobox.setEditable(True)
        self.Clear_combobox.setObjectName("Clear_combobox")
        self.Clear_combobox.addItem("")
        self.Clear_combobox.addItem("")
        self.Clear_combobox.addItem("")
        self.horizontalLayout_4.addWidget(self.Clear_combobox)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_4)
        self.delete_button = QtWidgets.QPushButton(self.preferenceBox)
        self.delete_button.setStyleSheet("background-color: red;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px 10px;")
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_9.addWidget(self.delete_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Zeros_radioButton = QtWidgets.QRadioButton(self.preferenceBox)
        self.Zeros_radioButton.setObjectName("Zeros_radioButton")
        self.horizontalLayout_5.addWidget(self.Zeros_radioButton)
        self.Poles_radioButton = QtWidgets.QRadioButton(self.preferenceBox)
        self.Poles_radioButton.setObjectName("Poles_radioButton")
        self.horizontalLayout_5.addWidget(self.Poles_radioButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.preferenceBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.mag_slider = QtWidgets.QSlider(self.preferenceBox)
        self.mag_slider.setOrientation(QtCore.Qt.Horizontal)
        self.mag_slider.setObjectName("mag_slider")
        self.horizontalLayout_6.addWidget(self.mag_slider)
        self.mag_LCD = QtWidgets.QLCDNumber(self.preferenceBox)
        self.mag_LCD.setObjectName("mag_LCD")
        self.horizontalLayout_6.addWidget(self.mag_LCD)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.preferenceBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.phase_slider = QtWidgets.QSlider(self.preferenceBox)
        self.phase_slider.setOrientation(QtCore.Qt.Horizontal)
        self.phase_slider.setObjectName("phase_slider")
        self.horizontalLayout_7.addWidget(self.phase_slider)
        self.phase_LCD = QtWidgets.QLCDNumber(self.preferenceBox)
        self.phase_LCD.setObjectName("phase_LCD")
        self.horizontalLayout_7.addWidget(self.phase_LCD)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.preferenceBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.add_conjugates = QtWidgets.QPushButton(self.preferenceBox)
        self.add_conjugates.setStyleSheet("background-color: green;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px 10px;\n"
"")
        self.add_conjugates.setObjectName("add_conjugates")
        self.horizontalLayout_8.addWidget(self.add_conjugates)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addWidget(self.preferenceBox)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.magBox = QtWidgets.QGroupBox(self.design_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magBox.sizePolicy().hasHeightForWidth())
        self.magBox.setSizePolicy(sizePolicy)
        self.magBox.setObjectName("magBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.magBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.magBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Magnitude_graph = PlotWidget(self.magBox)
        self.Magnitude_graph.setObjectName("Magnitude_graph")
        self.verticalLayout.addWidget(self.Magnitude_graph)
        self.verticalLayout_5.addWidget(self.magBox)
        self.phasebox = QtWidgets.QGroupBox(self.design_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phasebox.sizePolicy().hasHeightForWidth())
        self.phasebox.setSizePolicy(sizePolicy)
        self.phasebox.setObjectName("phasebox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.phasebox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.phasebox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.Phase_graph = PlotWidget(self.phasebox)
        self.Phase_graph.setObjectName("Phase_graph")
        self.verticalLayout_6.addWidget(self.Phase_graph)
        self.verticalLayout_5.addWidget(self.phasebox)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        self.gridLayout_2.addWidget(self.design_box, 0, 0, 1, 1)
        self.tabWidget.addTab(self.design_tab, "")
        self.correction_tab = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.correction_tab.setPalette(palette)
        self.correction_tab.setObjectName("correction_tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.correction_tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.correction_tab)
        self.groupBox.setStyleSheet("QGroupBox::pane {\n"
"    border: none;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.Zplane_box_2 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Zplane_box_2.sizePolicy().hasHeightForWidth())
        self.Zplane_box_2.setSizePolicy(sizePolicy)
        self.Zplane_box_2.setObjectName("Zplane_box_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Zplane_box_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.z_plane_2 = PlotWidget(self.Zplane_box_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_plane_2.sizePolicy().hasHeightForWidth())
        self.z_plane_2.setSizePolicy(sizePolicy)
        self.z_plane_2.setMinimumSize(QtCore.QSize(264, 264))
        self.z_plane_2.setMaximumSize(QtCore.QSize(253, 16777215))
        self.z_plane_2.setObjectName("z_plane_2")
        self.verticalLayout_11.addWidget(self.z_plane_2)
        self.horizontalLayout_21.addWidget(self.Zplane_box_2)
        self.mag_box = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mag_box.sizePolicy().hasHeightForWidth())
        self.mag_box.setSizePolicy(sizePolicy)
        self.mag_box.setObjectName("mag_box")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.mag_box)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_13 = QtWidgets.QLabel(self.mag_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        spacerItem4 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.Magnitude_graph_2 = PlotWidget(self.mag_box)
        self.Magnitude_graph_2.setObjectName("Magnitude_graph_2")
        self.verticalLayout_10.addWidget(self.Magnitude_graph_2)
        self.horizontalLayout_21.addWidget(self.mag_box)
        self.phase_box = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phase_box.sizePolicy().hasHeightForWidth())
        self.phase_box.setSizePolicy(sizePolicy)
        self.phase_box.setObjectName("phase_box")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.phase_box)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_16 = QtWidgets.QLabel(self.phase_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_19.addWidget(self.label_16)
        spacerItem5 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem5)
        self.verticalLayout_12.addLayout(self.horizontalLayout_19)
        self.Magnitude_graph_3 = PlotWidget(self.phase_box)
        self.Magnitude_graph_3.setObjectName("Magnitude_graph_3")
        self.verticalLayout_12.addWidget(self.Magnitude_graph_3)
        self.horizontalLayout_21.addWidget(self.phase_box)
        self.gridLayout_6.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.customBox = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customBox.sizePolicy().hasHeightForWidth())
        self.customBox.setSizePolicy(sizePolicy)
        self.customBox.setObjectName("customBox")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.customBox)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.lineEdit = QtWidgets.QLineEdit(self.customBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_20.addWidget(self.lineEdit)
        self.correction_apply_pushButton = QtWidgets.QPushButton(self.customBox)
        self.correction_apply_pushButton.setObjectName("correction_apply_pushButton")
        self.horizontalLayout_20.addWidget(self.correction_apply_pushButton)
        self.gridLayout_6.addWidget(self.customBox, 2, 0, 1, 1)
        self.filterBox = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterBox.sizePolicy().hasHeightForWidth())
        self.filterBox.setSizePolicy(sizePolicy)
        self.filterBox.setObjectName("filterBox")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.filterBox)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_15 = QtWidgets.QLabel(self.filterBox)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_18.addWidget(self.label_15)
        self.correction_combobox = QtWidgets.QComboBox(self.filterBox)
        self.correction_combobox.setObjectName("correction_combobox")
        self.correction_combobox.addItem("")
        self.correction_combobox.addItem("")
        self.correction_combobox.addItem("")
        self.correction_combobox.addItem("")
        self.correction_combobox.addItem("")
        self.correction_combobox.addItem("")
        self.horizontalLayout_18.addWidget(self.correction_combobox)
        self.correction_add_pushButton = QtWidgets.QPushButton(self.filterBox)
        self.correction_add_pushButton.setObjectName("correction_add_pushButton")
        self.horizontalLayout_18.addWidget(self.correction_add_pushButton)
        self.correction_delete_pushButton = QtWidgets.QPushButton(self.filterBox)
        self.correction_delete_pushButton.setObjectName("correction_delete_pushButton")
        self.horizontalLayout_18.addWidget(self.correction_delete_pushButton)
        self.gridLayout_6.addWidget(self.filterBox, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.correction_tab, "")
        self.Results_tab = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.Results_tab.setPalette(palette)
        self.Results_tab.setObjectName("Results_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Results_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.resultBox = QtWidgets.QGroupBox(self.Results_tab)
        self.resultBox.setObjectName("resultBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.resultBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.RealBox = QtWidgets.QGroupBox(self.resultBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RealBox.sizePolicy().hasHeightForWidth())
        self.RealBox.setSizePolicy(sizePolicy)
        self.RealBox.setObjectName("RealBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.RealBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.RealBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        spacerItem6 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.real_signal = PlotWidget(self.RealBox)
        self.real_signal.setObjectName("real_signal")
        self.verticalLayout_7.addWidget(self.real_signal)
        self.gridLayout_4.addWidget(self.RealBox, 0, 0, 1, 1)
        self.FilteredBox = QtWidgets.QGroupBox(self.resultBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilteredBox.sizePolicy().hasHeightForWidth())
        self.FilteredBox.setSizePolicy(sizePolicy)
        self.FilteredBox.setObjectName("FilteredBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.FilteredBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.FilteredBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        spacerItem7 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.filtered_signal = PlotWidget(self.FilteredBox)
        self.filtered_signal.setObjectName("filtered_signal")
        self.gridLayout_3.addWidget(self.filtered_signal, 1, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_12 = QtWidgets.QLabel(self.FilteredBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        self.speed_slider = QtWidgets.QSlider(self.FilteredBox)
        self.speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.speed_slider.setObjectName("speed_slider")
        self.horizontalLayout_14.addWidget(self.speed_slider)
        self.speed_LCD = QtWidgets.QLCDNumber(self.FilteredBox)
        self.speed_LCD.setObjectName("speed_LCD")
        self.horizontalLayout_14.addWidget(self.speed_LCD)
        self.gridLayout_3.addLayout(self.horizontalLayout_14, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.FilteredBox, 1, 0, 1, 1)
        self.loadingBox = QtWidgets.QGroupBox(self.resultBox)
        self.loadingBox.setObjectName("loadingBox")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.loadingBox)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.LoadBox = QtWidgets.QGroupBox(self.loadingBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadBox.sizePolicy().hasHeightForWidth())
        self.LoadBox.setSizePolicy(sizePolicy)
        self.LoadBox.setStyleSheet("")
        self.LoadBox.setObjectName("LoadBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.LoadBox)
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.touch_pad_button = QtWidgets.QRadioButton(self.LoadBox)
        self.touch_pad_button.setObjectName("touch_pad_button")
        self.verticalLayout_8.addWidget(self.touch_pad_button)
        self.load_button = QtWidgets.QRadioButton(self.LoadBox)
        self.load_button.setObjectName("load_button")
        self.verticalLayout_8.addWidget(self.load_button)
        self.verticalLayout_9.addWidget(self.LoadBox)
        spacerItem8 = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_9.addItem(spacerItem8)
        self.horizontalLayout_15.addLayout(self.verticalLayout_9)
        self.touch_pad = QtWidgets.QGraphicsView(self.loadingBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.touch_pad.sizePolicy().hasHeightForWidth())
        self.touch_pad.setSizePolicy(sizePolicy)
        self.touch_pad.setMaximumSize(QtCore.QSize(253, 16777215))
        self.touch_pad.setObjectName("touch_pad")
        self.horizontalLayout_15.addWidget(self.touch_pad)
        self.gridLayout_4.addWidget(self.loadingBox, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.resultBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Results_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 992, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Clear_combobox.setCurrentIndex(0)
        self.mag_slider.valueChanged['int'].connect(self.mag_LCD.display) # type: ignore
        self.phase_slider.valueChanged['int'].connect(self.phase_LCD.display) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Realtime Digital Filter"))
        self.label.setText(_translate("MainWindow", "Realtime Digital Filter"))
        self.label_5.setText(_translate("MainWindow", "Zeros-poles placement"))
        self.label_6.setText(_translate("MainWindow", "Clear"))
        self.Clear_combobox.setCurrentText(_translate("MainWindow", "all zeros"))
        self.Clear_combobox.setItemText(0, _translate("MainWindow", "all zeros"))
        self.Clear_combobox.setItemText(1, _translate("MainWindow", "all poles"))
        self.Clear_combobox.setItemText(2, _translate("MainWindow", "clear all"))
        self.delete_button.setText(_translate("MainWindow", "delete current"))
        self.Zeros_radioButton.setText(_translate("MainWindow", "Zeros"))
        self.Poles_radioButton.setText(_translate("MainWindow", "Poles"))
        self.label_7.setText(_translate("MainWindow", "magnitude"))
        self.label_8.setText(_translate("MainWindow", "Phase"))
        self.label_9.setText(_translate("MainWindow", "Conjugates"))
        self.add_conjugates.setText(_translate("MainWindow", "Add"))
        self.label_2.setText(_translate("MainWindow", "Magnitude Response"))
        self.label_4.setText(_translate("MainWindow", "Phase Response"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.design_tab), _translate("MainWindow", "Design"))
        self.label_13.setText(_translate("MainWindow", "Magnitude Response"))
        self.label_16.setText(_translate("MainWindow", "Corrected Phase"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "enter arbitary \'a\'"))
        self.correction_apply_pushButton.setText(_translate("MainWindow", "Apply"))
        self.label_15.setText(_translate("MainWindow", "Choose Filter"))
        self.correction_combobox.setItemText(0, _translate("MainWindow", "New Item"))
        self.correction_combobox.setItemText(1, _translate("MainWindow", "New Item"))
        self.correction_combobox.setItemText(2, _translate("MainWindow", "New Item"))
        self.correction_combobox.setItemText(3, _translate("MainWindow", "New Item"))
        self.correction_combobox.setItemText(4, _translate("MainWindow", "New Item"))
        self.correction_combobox.setItemText(5, _translate("MainWindow", "custom"))
        self.correction_add_pushButton.setText(_translate("MainWindow", "Add"))
        self.correction_delete_pushButton.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.correction_tab), _translate("MainWindow", "Correction"))
        self.label_10.setText(_translate("MainWindow", "Real Signal"))
        self.label_11.setText(_translate("MainWindow", "Filtered Signal"))
        self.label_12.setText(_translate("MainWindow", "Speed"))
        self.LoadBox.setTitle(_translate("MainWindow", "Preferences"))
        self.touch_pad_button.setText(_translate("MainWindow", "Touch Pad"))
        self.load_button.setText(_translate("MainWindow", "Load Signal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Results_tab), _translate("MainWindow", "Results"))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
